version: 2

sources:
  - name: staging
    database: dez-workspace-emi
     # For postgres:
      #database: production
    schema: trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: fhv_trips